config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  mount API => '/'
  mount GrapeSwaggerRails::Engine => '/swagger_doc'
  get 'xieyi/xieyi'    => 'xieyi#xieyi'
  get '/zhifu' => 'zhifu#zhifu'


  get 'formal/download' => 'codes#index'

  get 'web_pay/pay'     => 'web_pay#pay'
  get 'web_pay/other_pay' => 'web_pay#other_pay'
  get 'web_pay/success' => 'web_pay#success'
  get 'web_pay/cancel'  => 'web_pay#cancel'

  draw :new_api
  draw :web

  # 渠道管理
  namespace :channel do
    root "channel#index"
    get 'channel/index' => 'channel/index'
    resources :channel_users do
      resources  :transfers, only: [:index, :new, :create]
    end

    resources :channel_users do
      resources  :apply_cash_backs
    end

    post 'channel_users/create' => 'channel_users/create'
    #报备学校
    post 'school/addSchool' => 'school/addSchool'

    #消息提醒
    get 'message/admin_index' => 'message/admin_index'

    #报备pass
    get 'message/pass_school' => 'message/pass_school'
    #报备申请 失败
    get 'message/nopass_school' => 'message/nopass_school'

    #转账pass
    get 'message/pass_tx' => 'message/pass_tx'

    #渠道商报备记录
    get 'message/channel_baobei' => 'message/channel_baobei'

    #添加新学校
    post 'school/schoolAdd' => 'school/schoolAdd'

    #申请提现
    post 'school/apply_cash_ajax' => 'school/apply_cash_ajax'

    #学校是否已报备
    post 'school/checkSchool' => 'school/checkSchool'

    #根据学校id查看用户注册信息
    post 'school/show_ajax' => 'school/show_ajax'

    #用户注册
    get 'sessions/register' => 'sessions/register', as: :register

    #登录
    post 'sessions/checklogin' => 'sessions/checklogin'

    post 'sessions/doreg' => 'sessions/doreg'

    resources :school, only: [:show,:new, :create]

    resource :session, only: [:new, :create, :destroy]
   end

  namespace :admin do
    get "admin/index" => 'admin/index'
    post 'admin/index_ajax' => 'admin/index_ajax'
    get 'admin/show' => 'admin/show'
    patch 'admin/update' => 'admin/update'
    get 'admin/changedistrict' => 'admin/changedistrict'
    get 'admin/changepwd' => 'admin/changepwd'
    get 'admin/dochangepwd' => 'admin/dochangepwd'
    get 'admin/delchannel' => 'admin/delchannel'
    post 'admin/forbidden' => 'admin/forbidden'
  end

  namespace :new_api do
    scope module: :v1 do
      namespace :users do
        resources :sms_codes, only: [:create]
        resources :sessions, only: [:create]
      end
    end
  end



  get  '/share_article/:id', to: 'shares#share_article', as: :share_article
  get  '/share_record/:id',  to: 'shares#share_record',  as: :share_record
  get  '/share_dynamic/:id', to: 'shares#share_dynamic', as: :share_dynamic
  get  '/share_profile/:id', to: 'shares#share_profile', as: :share_profile

  get  '/webhooks', to: 'pings#test',     as: :test
  post '/webhooks', to: 'pings#webhooks', as: :webhooks
  resource :invites, only: [:show, :create]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/ohmymissing'
end

app/controllers/channel/channel_admin_controller.rb
class Channel::ChannelAdminController < ActionController::Base

  def sigined_in?
    !current_user.nil?
  end
  def current_user
    @current_user ||= ChannelUser.find_by_token(cookies[:token]) if cookies[:token]
  end

  def authenticate!
    redirect_to new_channel_session_path, alert: '请先登录哦' unless current_user
  end

  #是否是渠道商
  def ischannel?
    if current_user.admin?
      redirect_to new_channel_session_path
    end
  end

  #是否是管理员
  def isadmin?
      redirect_to new_channel_session_path unless current_user.nil? || current_user.admin?
  end
  helper_method :current_user

end

app/controllers/channel/message_controller.rb
module Channel
  class MessageController < ChannelAdminController
    before_action :authenticate! 
    before_action :isadmin?, only: [:admin_index, :pass_school, :nopass_school, :pass_tx]

    def admin_index
      @apply_cash_backs = ApplyCashBack.order('id desc').page(params[:page]).per(10)
      @channel_schools=ChannelSchool.order('id desc').page(params[:page]).per(10)
    end


    #报备通过
    def pass_school
      school_id=params[:id]
      channel_school=ChannelSchool.find(school_id)
      channel_school.passed=true
      if channel_school.save
        render(:json => 'success', :layout => false)
      else
        render(:json => 'fail', :layout => false)
      end
    end

    #报备不通过
    def nopass_school
      school_id=params[:id]
      channel_school=ChannelSchool.find(school_id)
      channel_school.passed=2
      channel_school.reason=params[:reason]
      if channel_school.save
        render(:json => 'success', :layout => false)
      else
        render(:json => 'fail', :layout => false)
      end
    end

    #转账
    def pass_tx
      apply = ApplyCashBack.find(params[:id])
      apply.passed=true

      #添加到转账记录表
      transfer = current_user.transfers.build(collector_id:  apply.channel_user.id, amount: apply.amount)

      if apply.save && transfer.save
        render(:json => 'success', :layout => false)
      else
        render(:json => 'fail', :layout => false)
      end
    end

    #渠道商报备记录

    def channel_baobei
      @schools=@current_user.channel_schools.page(params[:page]).per(10)
    end

    def xieyi
      render layout: false
    end
  end
end

app/controllers/channel/school_controller.rb
module Channel
  class SchoolController < ChannelAdminController
    before_action :authenticate!
    #before_action :ischannel?

    def new
      @channel_schools_count=current_user.channel_schools.count
      @num = Config.first.num
    end

    def show

      if @current_user.admin
        @school = School.find(params[:id])
        @year=Time.new.year
        @month=Time.new.month
        return false;
      end


      arr=[]

      @current_user.channel_schools.each do |school|
        arr.push(school.school.id)
      end

      if !arr.include?(params[:id].to_i)
        redirect_to channel_channel_index_url
        return false
      end

      @school = School.find(params[:id])

      @year=Time.new.year
      @month=Time.new.month
    end



    def show_ajax
      @date = params[:date]
      @type = params[:type]
      @tmptime = Time.parse(@date);

    end

    #报备学校
    def addSchool
      ids=params[:ids]

      result=JSON.parse(ids)

      result.each do |res|
        n = ChannelSchool.new(channel_user_id: @current_user.id, school_id: res)
        n.save
      end

      render(:json => 'ok', :layout => false)
    end


    #学校是否已报备
    def checkSchool
      school_id=params[:school_id]
      channel_school = ChannelSchool.find_by(school_id: school_id)
      if channel_school && channel_school.passed
        render(:json => 'yes', :layout => false)
      else
        render(:json => 'no', :layout => false)
      end
    end

    #添加新学校
    def schoolAdd
      district = District.find(params[:district_id])

      if School.find_by(name: params[:name], district_id: params[:district_id])
        render(:json => 'token', :layout => false)
        return false;
      end

      school = district.schools.build(:name => params[:name])
      if school.save
        render(:json => school.id, :layout => false)
      else
        render(:json => 'fail', :layout => false)
      end

    end


    #申请提现
    def apply_cash_ajax
      amount= params[:amount].to_i
      apply = @current_user.apply_cash_backs.build
      apply.amount=params[:amount].to_i
      apply.alipay=params[:alipay]
      if apply.save
        @cash = @current_user.channel_user_cash_back
        @cash.amount  -= amount
        @cash.used  += amount
        @cash.save
        render(:text => 'success', :layout => false)
      else
        render(:text => 'fail', :layout => false)
      end
    end
  end
end

app/controllers/channel/sessions_controller.rb
class Channel::SessionsController < Channel::ChannelAdminController
  def new
    render layout: false
  end

  def create
    user = ChannelUser.find_by_email(params[:email])

    cookies.permanent[:token] = user.token
    if user.admin?
      redirect_to admin_admin_index_url
    else
      redirect_to channel_channel_index_url
    end

  end

  #登录check
  def checklogin
    user = ChannelUser.find_by_email(params[:email])

    if user.nil? || !user.authenticate(params[:password])
      render(:text => '账号或密码错误', :layout => false)
      return false;
    end

    if user.phone != params[:phone]
      render(:text => '手机号不存在', :layout => false)
      return false
    end

    # if user.status == 'no'
    #   render(:text => '您的账号存在异常,请联系渠道管理员呀 021-61521541', :layout => false)
    #   return false
    # end

    # if !YunPian.verify(user.phone, params[:code])
    #   render(:text => '验证码错误', :layout => false)
    #   return false
    # end

    render(:text => 'success', :layout => false)

  end

  #注册
  def register

  end

  #处理添加渠道商
  def doreg
      @channel_user = ChannelUser.new()
      @channel_user.name=params[:name]
      @channel_user.email=params[:email]
      @channel_user.phone=params[:phone]
      @channel_user.password=params[:password]
      @channel_user.district_id=params[:district]
      @channel_user.company=params[:type]

      if ChannelUser.find_by(phone: params[:phone]) || ChannelUser.find_by(email: params[:email])
        redirect_to :back, :notice => "邮箱或手机号已存在!"
        return false;
      end

      if @channel_user.save
        redirect_to :back, :notice => 'success'
      else
        redirect_to :back, :notice => '注册失败,请重新注册'
      end
    end

  def destroy
    cookies.delete(:token)
    redirect_to new_channel_session_path
  end
end

app/views/channel/channel/index.html.erb
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title>欢乐诵渠道管理系统</title>
  <!--提现的样式-->
  <link rel="stylesheet" href="/css/lanrenzhijia.css" media="all">
  <link rel="stylesheet" href="/css/qd_welcome.css" media="all">
  <script src="/dist/js/jquery.min.js"></script>
  <%= javascript_include_tag 'application', "data-turbolinks-track" => false %>

</head>

<body style='border-top:2px solid red;'>
<p class='top'>
  <span class='p1'>渠道用户数据</span>
  <span class='s2'><%= current_user.name%>,您好</span>
  <span class='s1'><%=link_to "退出登录|",channel_session_path,class:'s1', method: :delete, :confirm => "Are you sure ?" %></span>
  <span class='s1'>  <%= link_to "提现记录|",channel_channel_user_apply_cash_backs_path(current_user), class: 's1' %></span>
  <!-- <span class='s1' id='tx'>申请提现|</span> -->
  <span class='s1'> <%= link_to "学校报备|", new_channel_school_path %></span>
  <%= link_to "个人中心 |",admin_admin_show_path(:id => current_user.id), class: 's1' %>
  <%= link_to "首页|",channel_channel_index_url, class: 's1' %>
<div class='clear'></div>
</p>
<div>
  <p class='hc l'><%= current_user.name %>, 您好</p>
  <p class='l' style='margin-top:45px;margin-left:15px;'>
    <sub style="width:250px;height:auto;display:block">你一共报备了<%= @schoolsCount %>
      所学校，<%= link_to "添加新学校?", new_channel_school_path %></sub></p>
  <div class='clear'></div>
</div>

<div>
  <div class='l' style='width:630px;min-height:430px;padding-left:40px;'>
    <p class='bao'>您报备的学校用用户数据详情</p>
    <div style="min-height:340px">
      <% @schools.each do |school| %>
          <a href="付费详情界面.html">
            <div class='xl w_bb'>
              <div class='l' style=''>
                <p class="w_school"><%= school.school.try(:district).try(:name)+school.school.name %></p>
                <p class="w_dist"><%= school.school.try(:district).try(:city).try(:name) + school.school.try(:district).try(:name) %></p>
              </div>

              <div class='l' ;>
                <p class="w_num"><%= school.school.vip_count %></p>
                <p class="w_reg">已注册: <%= school.school.user_count %></p>
              </div>

              <div class="w_info">
                <%= link_to channel_school_path(school.school_id) do %>
                    <img src="/dist/info.png" width="76" height="69"/>
                <% end %>
              </div>
            </div>
          </a>

      <% end %>
    </div>
    <div class='clear'></div>
    <div class='railspage'>
      <%= paginate @schools %>
    </div>
  </div>

<!--
  搜索
  <div style='float:left;min-height:200px;width:350px;margin-left:60px'>
    <p style='font-size:16px;'>快速查找你要查看的信息</p>
    <p style='font-size:12px;margin-top:15px'>根据地区,学校名称进行搜素，在文本框内输入信息</p>
    <p>
      <input class="w_search">
      <button style='width:45px;height:35px;background:url(./dist/search.png) no-repeat;border:none;border-radius:3px;position:relative;left:-52px;top:0.5px;'>
        &nbsp;</button>
    </p>
  </div>
 -->
  <div class='clear'></div>
</div>

<div class='minfo'>
  注册总计: <span class='f13f4b'><%= current_user.user_count%>人</span>
  <!-- 总收益: <span class='f13f4b'>￥<%= @totalAmount%></span> 可提现: <span class='f13f4b'>￥<%= @canApply%></span> -->
</div>

<!---begin提现-->
<div class="theme-popover-tx">
  <div class="theme-poptit">
    <a href="javascript:;" title="关闭" class="close">×</a>
    <h3>提现</h3>
  </div>
  <div class="theme-popbod dform-tx">
    <p>
      <span class="pf">支付 宝 账号:</span>
      <input type="text" id="alipay" class="acount">
    </p>

    <p style="margin-bottom:0px;">
      <span class="pf">提&nbsp; 现&nbsp; 金&nbsp; 额:</span> <input class='money' id='money' type='text'> 元
    <div class="info">可提现金额: <span class="f13f4b" id="cantx">

        <% if @current_user.try(:channel_user_cash_back) %>
           <%= @current_user.try(:channel_user_cash_back).try(:amount) || 0 %>
        <% else %>
          0
        <% end %>
      </span>元
    </div>
    </p>

    <p>
      <span class="pf">提&nbsp; 现&nbsp; 信&nbsp; 息:</span> <span class='money1' id="txinfo">0元</span>
    <div class="ipf" style="display:none"><img src="/dist/tan.png"></div>
    </p>

    <p class="zp">
      <button class='z-btn'>提交申请</button>
    </p>

  </div>
</div>
<div class="theme-popover-mask"></div>
<!---end-->

<div class='footer'>
  Copyright ©2016-2018 欢乐诵
</div>

<script src="/dist/js/tx.js"></script>

</body>
</html>