config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  mount API => '/'
  mount GrapeSwaggerRails::Engine => '/swagger_doc'
  get 'xieyi/xieyi'    => 'xieyi#xieyi'
  get '/zhifu' => 'zhifu#zhifu'


  get 'formal/download' => 'codes#index'

  get 'web_pay/pay'     => 'web_pay#pay'
  get 'web_pay/other_pay' => 'web_pay#other_pay'
  get 'web_pay/success' => 'web_pay#success'
  get 'web_pay/cancel'  => 'web_pay#cancel'

  draw :new_api
  draw :web

  # 渠道管理
  namespace :channel do
    root "channel#index"
    get 'channel/index' => 'channel/index'
    resources :channel_users do
      resources  :transfers, only: [:index, :new, :create]
    end

    resources :channel_users do
      resources  :apply_cash_backs
    end

    post 'channel_users/create' => 'channel_users/create'
    #报备学校
    post 'school/addSchool' => 'school/addSchool'

    #消息提醒
    get 'message/admin_index' => 'message/admin_index'

    #报备pass
    get 'message/pass_school' => 'message/pass_school'
    #报备申请 失败
    get 'message/nopass_school' => 'message/nopass_school'

    #转账pass
    get 'message/pass_tx' => 'message/pass_tx'

    #渠道商报备记录
    get 'message/channel_baobei' => 'message/channel_baobei'

    #添加新学校
    post 'school/schoolAdd' => 'school/schoolAdd'

    #申请提现
    post 'school/apply_cash_ajax' => 'school/apply_cash_ajax'

    #学校是否已报备
    post 'school/checkSchool' => 'school/checkSchool'

    #根据学校id查看用户注册信息
    post 'school/show_ajax' => 'school/show_ajax'

    #用户注册
    get 'sessions/register' => 'sessions/register', as: :register

    #登录
    post 'sessions/checklogin' => 'sessions/checklogin'

    post 'sessions/doreg' => 'sessions/doreg'

    resources :school, only: [:show,:new, :create]

    resource :session, only: [:new, :create, :destroy]
   end

  namespace :admin do
    get "admin/index" => 'admin/index'
    post 'admin/index_ajax' => 'admin/index_ajax'
    get 'admin/show' => 'admin/show'
    patch 'admin/update' => 'admin/update'
    get 'admin/changedistrict' => 'admin/changedistrict'
    get 'admin/changepwd' => 'admin/changepwd'
    get 'admin/dochangepwd' => 'admin/dochangepwd'
    get 'admin/delchannel' => 'admin/delchannel'
    post 'admin/forbidden' => 'admin/forbidden'
  end

  namespace :new_api do
    scope module: :v1 do
      namespace :users do
        resources :sms_codes, only: [:create]
        resources :sessions, only: [:create]
      end
    end
  end



  get  '/share_article/:id', to: 'shares#share_article', as: :share_article
  get  '/share_record/:id',  to: 'shares#share_record',  as: :share_record
  get  '/share_dynamic/:id', to: 'shares#share_dynamic', as: :share_dynamic
  get  '/share_profile/:id', to: 'shares#share_profile', as: :share_profile

  get  '/webhooks', to: 'pings#test',     as: :test
  post '/webhooks', to: 'pings#webhooks', as: :webhooks
  resource :invites, only: [:show, :create]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/ohmymissing'
end

app/views/admin/admin/changepwd.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <script src="/dist/js/jquery.min.js"></script>
  <%= javascript_include_tag 'application', "data-turbolinks-track" => false %>
  <link rel="stylesheet" href="/css/school_fufeixiangqing.css" media="all">
  <style>


    h1 {
      font-size: 18px;
      color: #666666;
      text-align: left;
      margin: 40px;
    }

    div {
      margin-left: 40px;
    }

    select {
      /*Chrome和Firefox里面的边框是不一样的，所以复写了一下*/

      /*很关键：将默认的select选择框样式清除*/
      appearance: none;
      -moz-appearance: none;
      -webkit-appearance: none;

      /*为下拉小箭头留出一点位置，避免被文字覆盖*/
      margin-right: 15px;

      width: 200px;
      height: 35px;
      padding: 0 15px;
      -moz-border-radius: 6px;
      -webkit-border-radius: 6px;
      border-radius: 0px;
      background: #ffffff;
      border: 1px solid rgb(238, 238, 238);
      margin-left: 20px;

    }

    .inp {
      width: 200px;
      height: 35px;
      margin-left: 20px;
      padding-left: 10px;
    }

    .btn {
      width: 70px;
      height: 35px;
      line-height: 35px;
      background: #f2f2f2;
      color: #666666;
      border-radius:2px;
      text-align:center;
      margin-top:25px;
      font-size:14px;
      border:1px solid #f1f1f1;
    }

    .s1{
      width:90px;
    }
  </style>

  <title>欢乐诵渠道管理系统</title>

</head>

<body style='border-top:2px solid red;height:auto'>

<% if current_user.admin %>
  <p class="top">
  <span class="p1">系统管理员</span>
  <span class="s2"><%= current_user.name %>,您好</span>
  <span class="s1"><%= link_to "添加渠道商 |", new_channel_channel_user_path, class: 's1' %></a>
  </span><span class="s1"><%= link_to "退出登录 |", channel_session_path, class: 's1', method: :delete, :confirm => "Are you sure ?" %></span>
  <span class="s1" style="color:#ff5c5c"> <%= link_to "转账记录 |", channel_channel_user_transfers_path(current_user), class: 's1' %></span>
  <%= link_to "首页|", admin_admin_index_url, class: 's1' %>
  <div class='clear'></div>
  </p>
<% else %>
  <p class='top'>
  <span class='p1'>渠道用户数据</span>
  <span class='s2'><%= current_user.name%>,您好</span>
  <span class='s1'><%=link_to "退出登录|",channel_session_path,class:'s1', method: :delete, :confirm => "Are you sure ?" %></span>
  <span class='s1'>  <%= link_to "提现记录|",channel_channel_user_apply_cash_backs_path(current_user), class: 's1' %></span>
  <%= link_to "学校报备|", new_channel_school_path, class: 's1' %>
  <%= link_to "修改密码 |",admin_admin_changepwd_path(current_user), class: 's1' %>
  <%= link_to "首页|",channel_channel_index_url, class: 's1' %>
  <div class='clear'></div>
<% end %>

<hr style='background:#f7f7f7;height:5px;opacity:0.8;border-top:none;margin:20px 0px'/>

<h1>修改密码</h1>

<% if :notice %>
    <p style="margin:40px;color:#f13f4b" id="info"><%= notice %></p>
<% end %>

<div>
  请输入新密码: <input type="password" class="inp" id="pwd1"><br/>
  重复输入密码: <input type="password" class="inp" id="pwd2"><br/>
</div>
<button class="btn qysub" style="margin-left:40px;margin-bottom: 150px">确定</button>

<script>

  $('.btn').click(function(){
      var pwd1=$('#pwd1').val()
      var pwd2=$('#pwd2').val()

      if($.trim(pwd1)=='' || $.trim(pwd2)==''){
        $('#info').html('密码不能为空!').fadeIn(300).delay(3000).fadeOut(100);
        return false;
      }

      if (pwd1 != pwd2){
        $('#info').html('两次密码不一致 ,请重新输入').fadeIn(300).delay(3000).fadeOut(100);
        return false;
      }

    $.ajax({
      url:'/admin/admin/dochangepwd',
      method: 'GET',
      data: {
        password : pwd2
      },
      dataType: "text",
      success: function(data){
        if(data == 'success'){
          $('#info').html('修改密码成功').fadeIn(300).delay(3000).fadeOut(300);
        }else{
          $('#info').html('修改密码失败').show(300).delay(3000).hide(300);
        }
      }
    })


  })


</script>

</body>
</html>

app/views/admin/admin/index.slim
doctype 5
html lang="en"
  head
    meta charset="UTF-8"
    title 欢乐诵管理员首页
    = javascript_include_tag 'application', "data-turbolinks-track" => false
    link rel="stylesheet" href="/css/lanrenzhijia.css" media="all"
    link rel="stylesheet" href="/css/admin_root.css" media="all"
    link rel="stylesheet" href="/css/admin_channel.css" media="all"

    script src="/js/jquery.min.js" data-turbolinks-track="false",


  body style="border-top:2px solid red;"
  p.top
    span.p1 系统管理员
    span.s2 = current_user.name+",您好"
    span.s1
      = link_to "添加渠道商 |",new_channel_channel_user_path, class: 's1'
    span.s1#tx
      = link_to "退出登录 |",channel_session_path,class:'s1', method: :delete, :confirm => "Are you sure ?"
    span.s1 style="color:#ff5c5c"
      = link_to "转账记录 |",channel_channel_user_transfers_path(current_user),class:'s1'
    span.s1 style="color:#ff5c5c"
      = link_to "修改密码 |",admin_admin_changepwd_path, class: 's1'
    span.s1 style="color:#ff5c5c"
      = link_to "首页|",admin_admin_index_url, class: 's1'
    .clear

  hr.hr
  .tit
    p
      h3 = current_user.name+",您好"
      span
        | 你有
           #{@msgcount}
            条新消息未处理,
        = link_to "立即处理?", channel_message_admin_index_path, class:'f13f4b'

  div style="padding-left:40px;"
    .shai
      p.year
        i 年份：
        span.selected 不限
        - (2016..2020).to_a.each do |value|
          span = value
      p.month
        i 月份：
        span.selected 不限
        - (1..12).to_a.each do |value|
          span  = value
      p.type
        i 类型：
        span.selected 不限
        span 公司
        span 个人
      p.district
        span 区域:
        = select_tag "province", options_from_collection_for_select(@provinces, "id", "name"), prompt: "选择省"

        select#city name="city"
          option value= " " 选择市
        select#district name="district"
          option value= "" 选择区(县)
        bottom.admin_shaixuan 筛选
    .tab
      .qd
        span style='dispaly:block;float:left;font-size:16px;color:#333333' 渠道用户数据

        p style='float:right'
          |渠道商:
          span.f13f4b#channel_count = "0人"
      table width="920" cellspacing="0" cellpadding="10"
        thead
          tr
            th 序号
            th 名称
            th 地区
            th 公司/个人
            th 开通时间
            th 渠道资源
            th 注册用户
            th 开通会员
            th 详情
        tbody.con



      div.page.yahoo2#pager

.footer Copyright ©2016-2018 欢乐诵

  <div class="page yahoo2" id="pager">

  </div>

javascript:
  var province = $("#province"),city = $("#city");
  province.change(function(event){
    var province_id = province.val();
    if (province_id == " ")
      return
    else{
      $.ajax({
        url: '/api/v1/cities',
        method:'GET',
        data: { province_id: province_id},
        dataType: "json",
        success: function(data){
           var city = $("#city");
           city.empty();
             var dom = '<option value="">市</option>';
           $.each(data, function(k, v){
             dom += "<option value=" + v.id + ">" + v.name +"</option>";
           });
           console.log(dom);
           city.append(dom);
        }
      })
    }
  });

  city.change(function(event){
    console.log("city change")
    var city_id = city.val();
    if (city_id == " ")
      return
    else{
      $.ajax({
        url:'/api/v1/districts',
        method: 'GET',
        data: { city_id : city_id},
        dataType: "json",
        success: function(data){
          var district = $("#district");
          district.empty();
          var dom ='<option value="">区(县)</option>';
          $.each(data, function(k, v){
            dom += "<option value="+ v.id + ">" + v.name + "</option>";
          });
          console.log(dom);
          district.append(dom);
        }
      })
    }

  });

  $('.year >span').click(function () {
    $(this).addClass('selected').siblings().removeClass('selected');
  })

  $('.month >span').click(function () {
    $(this).addClass('selected').siblings().removeClass('selected');

  })

  $('.type >span').click(function () {
    $(this).addClass('selected').siblings().removeClass('selected');
  })

  $('.admin_shaixuan').click(function(){
    var year = $('.year > .selected').text();
    var month = $('.month > .selected').text();
    var type = $('.type > .selected').text();
    var district = $('#district').val();


    if(year == '不限'){
      year = ''
    }

    if(month == '不限'){
      month = ''
    }

    if(type=='不限'){
      type = ''
    }

    if(type == '公司'){
      type = 1
    }

    if (type == '个人'){
      type = 0
    }



    $.ajax({
      url: "/admin/admin/index_ajax",
      data: {
        years: year,
        month: month,
        type: type,
        district: district
      },
      type: 'post',
      dateType: 'json',
      success: function (data) {
        var dataObj = eval('(' + data + ')');
        total = dataObj.length
        $('#channel_count').html(total+'人')
        PageClick(1, total, '|', year,month, type,district)


      }
    })
  })

  $('.admin_shaixuan').trigger('click')




  PageClick = function (pageIndex, total, spanInteval, year, month, type,district) {
    $('#pager').show();
    $.ajax({
      url: "/admin/admin/index_ajax",
      data: {
        pageIndex: pageIndex,
        years: year,
        month: month,
        type: type,
        district: district
      },

      type: 'post',
      dateType: 'json',
      success: function (data) {
        $('.con').html('')
        var intPageIndex = parseInt(pageIndex) //索引从1开始

        var dataObj = eval('(' + data + ')');

        if(dataObj.length == 0){
          $('#pager').hide();
          return false;
        }


        con = ''

        $.each(dataObj, function (i, v) {
          con += "<tr><td>" + parseInt(i + 1) + "</td><td><a href='/admin/admin/show?id="+v.id+"'>"+v.name + "</a></td><td>" + v.address + "</td><td>" + v.company + "</td><td>" + v.created_at + "</td>" + "<td>" + v.channel_size + "</td><td>" + v.channel_reg + "</td><td>" + v.channel_vip + "</td><td class='goinfo' id=" + v.id + ">详情</td></tr>";
        })

        $('.con').html(con)

        goinfo();



        var pageS = total


        if (pageS % 10 == 0)
          pageS = pageS / 10
        else
          pageS = parseInt(total / 10) + 1

        $pager = $('#pager')
        $('#pager span').remove()
        $('#pager a').remove()

        if (intPageIndex == 1)
          $pager.append("<span class='disabled'>第一页</span>");
        else {
          var first = $("<a href='javascript:void(0)' first='" + 1 + "'>第一页</a>").click(function () {
            PageClick($(this).attr('first'), total, spanInteval, year, month, type,district);
            return false;
          });
          $pager.append(first);
        }

        //添加上一页
        if (intPageIndex == 1)
          $pager.append("<span class='disabled'>上一页</span>");
        else {
          var pre = $("<a href='javascript:void(0)' pre='" + (intPageIndex - 1) + "'>上一页</a>").click(function () {
            PageClick($(this).attr('pre'), total, spanInteval, year, month, type,district);
            return false;
          });
          $pager.append(pre);
        }

        //设置分页的格式  这里可以根据需求完成自己想要的结果
        var interval = spanInteval; //设置间隔
        var start = Math.max(1, intPageIndex - interval); //设置起始页
        var end = Math.min(intPageIndex + interval, pageS)//设置末页

        if (intPageIndex < interval + 1) {
          end = (2 * interval + 1) > pageS ? pageS : (2 * interval + 1);
        }

        if ((intPageIndex + interval) > pageS) {
          start = (pageS - 2 * interval) < 1 ? 1 : (pageS - 2 * interval);

        }

        //生成页码
        for (var j = start; j < end + 1; j++) {
          if (j == intPageIndex) {
            var spanSelectd = $("<span class='current'>" + j + "</span>");
            $pager.append(spanSelectd);
          } //if
          else {
            var a = $("<a href='javascript:void(0)'>" + j + "</a>").click(function () {
              PageClick($(this).text(), total, spanInteval, year, month, type,district);
              return false;
            });
            $pager.append(a);
          } //else
        } //for


        //一页
        if (intPageIndex == total) {
          $pager.append("<span class='disabled'>下一页</span>");
        } else {
          var next = $("<a id='next' href='javascript:void(0)' next='" + (intPageIndex + 1) + "'>下一页</a>").click(function () {
            PageClick($(this).attr("next"), total, spanInteval, year, month, type,district);
            return false;
          });
          $pager.append(next);
        }

        if (intPageIndex == pageS) {
          $pager.append("<span class='disabled'>最后一页</span>");
          $('#next').hide()
        } else {
          var last = $("<a id='last' href='javascript:void(0)' last='" + pageS + "'>最后一页</a>").click(function () {
            PageClick($(this).attr("last"), total, spanInteval, year, month, type,district);
            return false;
          });
          $pager.append(last);
        }

      }
    })
  }

  function goinfo() {
    $('.goinfo').click(function () {
      var id = $(this).attr('id')
      window.location.href='/channel/channel_users/'+id;
    })
  }

app/views/admin/admin/show.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <script src="/dist/js/jquery.min.js"></script>
  <%= javascript_include_tag 'application', "data-turbolinks-track" => false %>
  <link rel="stylesheet" href="/css/school_fufeixiangqing.css" media="all">
  <style>


    h1 {
      font-size: 18px;
      color: #666666;
      text-align: left;
      margin: 40px;
    }

    div {
      margin-left: 40px;
    }

    select {
      /*Chrome和Firefox里面的边框是不一样的，所以复写了一下*/

      /*很关键：将默认的select选择框样式清除*/
      appearance: none;
      -moz-appearance: none;
      -webkit-appearance: none;

      /*为下拉小箭头留出一点位置，避免被文字覆盖*/
      margin-right: 15px;

      width: 200px;
      height: 35px;
      padding: 0 15px;
      -moz-border-radius: 6px;
      -webkit-border-radius: 6px;
      border-radius: 0px;
      background: #ffffff;
      border: 1px solid rgb(238, 238, 238);
      margin-left: 20px;

    }

    .inp {
      width: 200px;
      height: 35px;
      margin-left: 20px;
      padding-left: 10px;
    }

    .delbtn {
      width: 100px;
      height: 35px;
      line-height: 35px;
      background: #f13f4b;
      color: #ffffff;
      border-radius: 5px;
      text-align: center;
      margin-top: 25px;
      font-size: 14px;
      border: 1px solid #f1f1f1;
      float: right;
    }

    .forbidden{
      width: 100px;
      height: 35px;
      line-height: 35px;
      background: #f13f4b;
      color: #ffffff;
      border-radius: 5px;
      text-align: center;
      margin-top: 25px;
      font-size: 14px;
      border: 1px solid #f1f1f1;
      float: right;
      margin-right:10px;
    }

    .btn {
      width: 70px;
      height: 35px;
      line-height: 35px;
      background: #f2f2f2;
      color: #666666;
      border-radius: 2px;
      text-align: center;
      margin-top: 25px;
      font-size: 14px;
      border: 1px solid #f1f1f1;
    }

      .topdiv{
        width:80%;
        height:40px;
        margin:0px;
      }

      .s1{
        width:90px;
      }
  </style>

  <title>欢乐诵渠道管理系统</title>

</head>

<body style='border-top:2px solid red;height:auto'>

<% if current_user.admin? %>
  <p class="top">
    <span class="p1">修改信息</span>
    <span class="s2"><%= current_user.name %>,您好</span>
    <span class="s1"><%= link_to "添加渠道商 |", new_channel_channel_user_path, class: 's1' %></a>
    </span><span class="s1"><%= link_to "退出登录 |", channel_session_path, class: 's1', method: :delete, :confirm => "Are you sure ?" %></span>
    <span class="s1" style="color:#ff5c5c"> <%= link_to "转账记录 |", channel_channel_user_transfers_path(current_user), class: 's1' %></span>
    <%= link_to "首页|", admin_admin_index_path, class: 's1' %>
  <div class='clear'></div>
  </p>
<% else %>
  <p class='top'>
  <span class='p1'>渠道用户数据</span>
  <span class='s2'><%= current_user.name%>,您好</span>
  <span class='s1'><%=link_to "退出登录|",channel_session_path,class:'s1', method: :delete, :confirm => "Are you sure ?" %></span>
  <span class='s1'>  <%= link_to "提现记录|",channel_channel_user_apply_cash_backs_path(current_user), class: 's1' %></span>

 <%= link_to "学校报备|", new_channel_school_path, class: 's1' %>
  <%= link_to "个人中心 |",admin_admin_show_path, class: 's1' %>
  <%= link_to "首页|",channel_channel_index_url, class: 's1' %>
  <div class='clear'></div>
<% end %>


<hr style='background:#f7f7f7;height:5px;opacity:0.8;border-top:none;margin:20px 0px'/>

<div class="topdiv">
  <h1>修改基本商信息</h1>
  <% if current_user.admin? %>
      <button class="delbtn">删除该渠道商</button>
      <% if @status == 'yes' || !@status %>
        <button class="forbidden">
          禁用
        </button>
      <% else %>
        <button class="forbidden">
          启用
        </button>
      <% end %>
  <% end %>
</div>

<% if :notice %>
    <p style="margin:40px;color:#f13f4b"><%= notice %></p>
<% end %>

<div>
  <%= form_for(@channel_user, url: admin_admin_update_path(:id => @channel_user.id)) do |f| %>

      <p>
        <%= f.label '名称:' %>
        <%= f.text_field :name, class: 'inp' %>
      </p>

      <p>
        <%= f.label '邮箱:' %>
        <%= f.text_field :email, class: 'inp' %>
      </p>


      <p>
        <%= f.label '手机:' %>
        <%= f.text_field :phone, class: 'inp' %>
      </p>

      <p>
        <%= f.label '类型:' %>
        <%= f.select :company, @com %>
      </p>

      <p>
        <%= f.label '密码:' %>
        <%= f.password_field :password, class: 'inp' %>
      </p>

      <p>
        <%= f.submit '修改', class: 'btn' %>
      </p>
  <% end %>
</div>

<h1>修改渠道商所在区域</h1>

<p style="margin:40px;color:#f13f4b" id="info"></p>

<div style="margin-left:20px">
  <%= select_tag "province", options_from_collection_for_select(Province.all, "id", "name"), prompt: "选择省" %>

  <br/>
  <select name="city" id="city">
    <option value="">选择市</option>
  </select>
  <br/>
  <select name="district" id="district">
    <option value="">选择区(县)</option>
  </select>


</div>
<button class="btn qysub" style="margin-left:40px;margin-bottom: 150px">修改</button>

<script>

  var province = $("#province"), city = $("#city");
  province.change(function (event) {
    var province_id = province.val();
    if (province_id == " ")
      return
    else {
      $.ajax({
        url: '/api/v1/cities',
        type: 'get',
        data: {province_id: province_id},
        dataType: "json",
        success: function (data) {
          var city = $("#city");
          city.empty();
          var dom = '<option value="">选择市</option>';
          $.each(data, function (k, v) {
            dom += "<option value=" + v.id + ">" + v.name + "</option>";
          });
          city.append(dom);
        }
      })
    }
  });

  city.change(function (event) {
    console.log("city change")
    var city_id = city.val();
    if (city_id == " ")
      return
    else {
      $.ajax({
        url: '/api/v1/districts',
        type: 'get',
        data: {city_id: city_id},
        dataType: "json",
        success: function (data) {
          var district = $("#district");
          district.empty();
          var dom = '<option value="">选择区(县)</option>';
          $.each(data, function (k, v) {
            dom += "<option value=" + v.id + ">" + v.name + "</option>";
          });
          district.append(dom);
        }
      })
    }

  });


</script>

<script>
  $('.qysub').click(function () {

    if ($('#district').val() == '') {
      $('#info').html('请先选择区域').show(300).delay(3000).hide(300);
      return false;
    }

    $.ajax({
      url: '/admin/admin/changedistrict',
      type: 'get',
      data: {
        district_id: $('#district').val(),
        channel_user_id: "<%= @channel_user.id %>"
      },
      dataType: "text",
      success: function (data1) {
        if (data1 == 'success') {
          $('#info').html('修改区域成功').fadeIn(300).delay(3000).fadeOut(300);
        } else {
          $('#info').html('修改区域失败').show(300).delay(3000).hide(300);
        }
      }
    })
  })

    $('.delbtn').click(function(){
      if(confirm("确定要删除该渠道商吗")){
        $.ajax({
          url:'/admin/admin/delchannel',
          method: 'GET',
          data: {
            id : "<%= @channel_user_id %>"
          },
          dataType: "text",
          success: function(data){
            if(data== 'success'){
              alert('删除渠道商成功!');
              window.location.href='/admin'
            }else{
              alert('删除渠道商失败!')
            }
          }
        })
      }
    })

     $('.forbidden').click(function(){
      if(confirm("确定要操作？")){
        $.ajax({
          url:'/admin/admin/forbidden',
          type: 'post',
          data: {
            id : "<%= @channel_user_id %>"
          },

          dataType: "text",
          success: function(data){
            if(data== 'success'){

               var con = $.trim($('.forbidden').text());

              if(con == '禁用'){
                $('.forbidden').text('启用')
              }

              if(con == '启用'){
                $('.forbidden').text('禁用')
              }


            }else{
              return false
            }
          }
        })
      }

    })

</script>

</body>
</html>